### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by kant01ne**
@mmartinic

### CODE REVIEW

**Review by mmartinic — APPROVED** [review]

**Comment by lorcan** [comment]
This PR looks like a mini-blog post... What about a short piece on how we do open-source and what constitutes a good PR?

**Comment by kant01ne** [comment]
Interesting idea @lorcan. That could be a section in [developers docs](https://developers.intercom.com) on which we link all of our sdks:

### Contributing

[Guidelines for open source contributions](https://developers.intercom.com/contributing)

**Comment by lorcan** [comment]
👍 why not both 👯

**Comment by kant01ne** [comment]
@choran interesting ideas here

**Pull request merged**
